---
- shell: host myip.opendns.com resolver1.opendns.com | grep address | cut -d' ' -f4
  register: my_ip_address

- set_fact: 
    my_ip_address={{ my_ip_address.stdout }}

- debug: 
    var: my_ip_address

- name: Gopher Server
  apt:
    package: "pygopherd"
    state: latest
  when: SECOPS_MOLECULE_TEST is not defined

- name: Template pygopherd.conf
  template:
    src: templates/pygopherd.conf.j2
    dest: /etc/pygopherd/pygopherd.conf
    owner: root
    group: root
    mode: '0644'