---

# https://prgmr.com/blog/gopher/2018/11/09/setting-up-gopherserver.html

- shell: host myip.opendns.com resolver1.opendns.com | grep address | cut -d' ' -f4
  register: my_ip_address

- set_fact: 
    my_ip_address={{ my_ip_address.stdout }}

- debug: 
    var: my_ip_address

- name: Gopher Server
  apt:
    package: "pygopherd"
    state: latest
  when: SECOPS_MOLECULE_TEST is not defined

- name: Template pygopherd.conf
  template:
    src: templates/pygopherd.conf.j2
    dest: /etc/pygopherd/pygopherd.conf
    owner: root
    group: root
    mode: '0644'

- name: Create a directory if it does not exist
  file:
    path: "/var/gopher"
    state: directory
    mode: '0755'

- name: Copy Gophermap to Server
  copy:
    src: files/gophermap
    dest: /var/gopher/gophermap
    owner: root
    group: root
    mode: 0644

- name: ensure pygopherd is running
  service:
    name: pygopherd
    state: started
  when: SECOPS_MOLECULE_TEST is not defined
