---
- name: Include variables
  include_vars:
    file: main.yml

- name: Set up some system packages
  include: packages.yml

- name: ensure apache is running
  service:
    name: httpd
    state: started
  when: SECOPS_MOLECULE_TEST is not defined

- name: Set up the web site
  include: sandy_website.yml
